version: "3.9"
volumes:
  postgres_data:
    driver: local
services:
  backend:
    build: .
    restart: always
    environment:
      - DB_HOST=db:5432
      - DB_NAME=auth
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PORT=5050
    ports:
      - "5050:5050"
    depends_on:
      - db
    links:
      - db


  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db_schema/psql/user.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
