[tool.black]
line-length = 100
target-version = ['py310']
experimental_string_processing = true

[tool.ruff]
line-length = 100

[tool.commitizen]
version = "1.0.0"
tag_format = "v$version"
version_files = [
  "pyproject.toml:version",
  "app/main.py:APP_VERSION"
]
update_changelog_on_bump = true

[tool.pytest.ini_options]
minversion = "7.3"
addopts = "-ra -q"
testpaths = [
    "tests",
]
